name: Docker Image CI

on:
  push:
    branches: [ v3-demo ]
  pull_request:
    branches: [ v3-demo ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker run -p 8000:8000 osjs/osjs:v3
